# Google App Engine Configuration for Artisan Hub Backend
runtime: python311
service: artisan-backend
instance_class: F4_1G

# Automatic scaling configuration
automatic_scaling:
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.65
  min_instances: 1
  max_instances: 10
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 80

# Environment variables
env_variables:
  # LLM Provider Configuration
  LLM_PROVIDER: "groq"
  OLLAMA_BASE_URL: "http://ollama:11434"

  # Database
  CHROMA_DB_PATH: "/tmp/chroma_db"

  # Server Configuration
  LOG_LEVEL: "INFO"
  CORS_ORIGINS: "https://your-frontend-domain.vercel.app"
  BACKEND_URL: "https://your-backend.appspot.com"

# VPC connector (if using Cloud SQL or private services)
# vpc_access_connector:
#   name: "projects/YOUR_PROJECT/locations/YOUR_REGION/connectors/YOUR_CONNECTOR"

# Handlers
handlers:
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301

# Health check
health_check:
  enable_health_check: true
  check_interval_sec: 30
  timeout_sec: 10
  unhealthy_threshold: 2
  healthy_threshold: 2
  restart_threshold: 60
  host: ""
